name: Auto Merge Pull Request


on:
    pull_request_review:
        types: [submitted]

jobs:
    auto-merge:
        runs-on: ubuntu-latest
        if: github.event.review.state == 'approved'
        steps:
            - name: Checkout Repos
              uses: actions/checkout@v2
            
            - name: Auto Merge PR
              uses: pascalgn/automerge-action@v0.14.3
              env:
                GITHUB_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}