run-name: run deploy and test

on:
  push:
    paths: 
        - 'force-app/**'

jobs:
    run-test-class:
        runs-on: ubuntu-latest
        steps:
          - uses:  actions/checkout@v2
            with:
                fetch-depth: 0
          - name: install-sfdx-clis
            run:
                npm install @salesforce/cli --global
          - name:  login to salesforce org
            run:
                sf login functions jwt --username ${{secrets.SALESFORCE_USERNAME}}  --keyfile JWT/server.key --clientid ${{secrets.SFDX_JWT_KEY}}
          - name: run deploy
            run: 
                sf deploy functions --connected-org zeusHubOrg
                
                