name: Validation Production

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'Deployment'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Salesforce CLI
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: |
        npm install -g sfdx-cli

    - name: Authenticate with Salesforce
      run: |
        sfdx force:auth:web:login --setalias myOrg --instanceurl${{ secrets.SALESFORCE_LOGIN_URL }}
        
    - name: Deploy changes to sandbox
      run: |
        sfdx force:source:deploy -p force-app -u myOrg -l RunLocalTests