name: Validation Production

on:
  pull_request:
    branches: 
      - Deployment
    paths: 
      - "force-app/**"
    
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validation on Deployment
        uses:  salesforce/sfdx-action@v1
        with: 
          SFDX_AUTH_URL : ${{secrets.SFDX_AUTH_URL}}
          DRY_RUN: true