name: Validation Production

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Salesforce CLI
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: |
        npm install -g sfdx-cli

    - name: Authenticate with Salesforce
      run: |
        sfdx force:auth:jwt:grant --clientid ${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwtkeyfile server.key --username ${{ secrets.SALESFORCE_USERNAME }} --setdefaultdevhubusername -a DevHub

    - name: Deploy changes to sandbox
      run: |
        sfdx force:source:deploy -p force-app -u ${{ secrets.SALESFORCE_USERNAME }} -l RunLocalTests